---
title: "Documentation for text alert scripts"
author: "Lisa Oshita"
date: "May 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Requirements for alert.py

The latest version of python needs to be installed. Instructions for python installation:

1. Download python [here](https://www.python.org/downloads/)
2. On the first screen of the python installer, the option "Add Python 3.6 to PATH" must be enabled
3. Click "Install Now"

Python packages, twilio and pandas, also need to be installed. Instructions for package installations:

1. Open the command prompt
2. Type "pip install twilio"
3. Type "pip install pandas"

The file containing the subscriber phone numbers must be in CSV format. 

# Description of how send.alert.R functions

The main function of send.alert.R that will be run is text.alert(). text.alert() takes the name of the file that contains pm10 values as a character string argument. After reading in the file, the function formats it and checks if the dates in the file are equal to the current date. If not, the function stops and returns the message, "Old file". If the dates are current, then the function sets all pm10 values that are greater than 800 to NA. It then checks if all pm10 values are less than 175. If true, the function stops and returns the message, "No text sent". If false, the function sets any pm10 values that are greater than 175 and that occurred before 8:00am, to NA. The function checks again if all values of pm10 are less than 175. If true, the function stops and returns, "No text sent". If false, the function reads in the log of text messages sent, and if a text was already sent that day, the function stops and returns, "Text already sent today". If not, the function initializes an empty data frame that will be used later on to store message information. Function then creates a batch file that calls and executes the alert.py file. The batch file is ran with the system2 function. The output of system2() is saved to "run". Output will be either a 0 if alert.py executed without error, or a 1 if there was an error. If there was an error, text alerts were not sent out at all, and the function will stop and return "Texts failed to send". If texts were sent successfully, the function will continue and the message log will be updated with the current date and time. The tw_get_messages_list() function from the twilio package will retrieve the entire message list from Twilio, and update the message log with the body of the messages sent. This log will then be appended to the existing log of texts called alert.log.csv. Lastly, the function will unlink the batch file created earlier. 

# Description of how alert.py functions

Script imports the twilio and pandas libraries. The function main reads in the csv of subscriber phone numbers. Only the columns "PHONE" and "DUST" will be read. The dtype argument of this function specifies that columns will be read in as character strings (str). The function then performs a series of string manipulation techniques on the "DUST" column. All white spaces are removed and all text is converted to lower case. All phone numbers that are complete (have at least 10 numbers) and indicated "yes" in the DUST column are kept. Leading ones are added to the phone numbers that don't have a leading one (numbers with less than 11 numbers). All phone numbers are then concatenated to the rest of the address string. All addresses are then put into a list called "full". The function then sends the SMS messages using that list.

The code snippet at the bottom of the python script just makes it so if alert.py is called, the main function is automatically ran (no need to call the function within alert.py). 

# Reasons why texts might fail to send

* Account SID, Token, Service SID might be incorrect. 

