---
title: "Wind Event Predictor"
author: "Lisa Oshita"
date: "October 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results='hide'}
# load packages
library(readr)
library(lubridate) # for working with dates
library(dplyr)
library(caret) # randomforest package needs to be installed 
```

# Objective

Build a model to predict wind event days, based on meteorological data. A wind event is defined as any day when the 24-hour average PM10 concentration at CDF exceeds the state standard, i.e. 50 ug/m3. 

# Load data

```{r}
s1.data <- read_csv("H:/TECH/Lisa/R/apcd.r/wind.event.predictor/forLisa.csv") # contains data from 2011 - 2017
cdf.master <- read_csv("H:/TECH/Lisa/R/apcd.r/wind.event.predictor/cdf.master.csv")
```

* maybe also include month variable

```{r}
# formatting s1.data
s1.data <- s1.data %>%
  mutate(date1 = lubridate::date(date)) %>%
  mutate(hour = lubridate::hour(date))

# converting data frame to wide format
# single date for each row, hours in the columns
d <- s1.data[s1.data$hour==0, c(9, 2, 3)]
names(d) <- c("date1", paste(names(d)[-1], 0, sep="."))

for(i in 1:23){
  dd <- s1.data[s1.data$hour==i, c(2, 3)]
  names(dd) <- paste(names(dd), i, sep=".")
  d <- cbind(d,dd)
}

rm(dd, i)

# 24 hour pm10 averages + creating binary did.exceed variable
pm10.averages <- s1.data %>%
  group_by(date1) %>%
  summarize(pm10.ave = mean(pm10.cdf, na.rm = TRUE)) %>%
  mutate(did.exceed = ifelse(pm10.ave >= 50, "yes", "no")) %>%
  select(-date1)


d <- cbind(d, pm10.averages)

# only using wd and ws at CDF for now, 5% of wd and ws for S1 are missing (think of ways for dealing with this - include variable for is.missing?) 

colnames(d)[1] <- "date"

# joining cdf.master
# cdf.master.subset <- cdf.master %>%
#   select(date, precip, s.rad, a.temp, rh, s.temp)
# 
# d <- d %>%
#   left_join(cdf.master.subset, by = "date")
# precip, s.rad, a.temp, rh, s.temp all have ~50% missing values
# remove these for now


# creating month variable + removing variables not to be included in the model
d <- d %>%
  mutate(month = lubridate::month(date)) %>%
  select(-pm10.ave)


# partition into training and test sets
# train on all years before 2015, test on 2015, 2016
train <- d %>% 
  filter(lubridate::year(date) < 2015) %>%
  select(-date) %>%
  mutate(did.exceed = as.factor(did.exceed))

test.x <- d %>% 
  filter(lubridate::year(date) >= 2015) %>%
  select(-date) %>%
  mutate(did.exceed = as.factor(did.exceed))
test.y <- test.x$did.exceed

test.x <- test.x %>% select(-did.exceed)
```

# Examining the response variable 

```{r}
prop.table(table(d$did.exceed))

prop.table(table(train$did.exceed))
# some class imbalance is present
```

```{r}
# random forest won't work with missing values 
train %>%
  filter(is.na(did.exceed))

# removing rows that contain NAs (only 82 rows contained NAs)
train <- na.omit(train) 
```



# Random Forest

```{r}
# parameter tuning
grid <- expand.grid(mtry = c(5, round(sqrt(ncol(d))), 
                              15, 25, 30))

tune.control <- trainControl(method = "cv", 
                             number = 5,
                             verboseIter = TRUE,
                             classProbs = TRUE)

set.seed(1)

start.tune <- Sys.time()
rf.tuning <- train(did.exceed ~ ., 
                   data = train, 
                   method = "ranger", # a form of random forests  ranger and e1071 packages need to be installed
                   tuneGrid = grid, 
                   ntree = c(500, 1000, 1500),
                   trControl = tune.control)
end.tune <- Sys.time()
```















